version: '3.2'

services:
  rabbitmq-01:
    image: rabbitmq-cluster:3.9.18-debian-10-r0
    hostname: rabbitmq01
    container_name: node-1
    tty: true
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=side_rabbit_cookie
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    extra_hosts:
      - "rabbitmq02:10.10.0.102"
      - "rabbitmq03:10.10.0.103"
    networks:
      rabbitmq:
        ipv4_address: 10.10.0.101

networks:
   rabbitmq:
    external: true