version: '3'
services:
  # nacos-server服务注册与发现，配置中心服务	
  docker-nacos-server:
    image: nacos/nacos-server:1.1.4
    container_name: nacos-server-3
    ports:
      - "8848:8848"
      - "9555:9555"
    networks: 
      - nacos_net
    restart: on-failure
    privileged: true
    environment:
      #PREFER_HOST_MODE: ip #如果支持主机名可以使用hostname,否则使用ip，默认也是ip
      SPRING_DATASOURCE_PLATFORM: mysql #数据源平台 仅支持mysql或不保存empty
      NACOS_SERVER_IP: 119.45.122.161 #多网卡情况下，指定ip或网卡
      NACOS_SERVERS: 101.34.180.133:8848 106.52.23.202:8848 119.45.122.161:8848 #集群中其它节点[ip1:port ip2:port ip3:port]
      # 以下是主从集群的mysql配置方法
      MYSQL_MASTER_SERVICE_HOST: 101.34.180.133 #mysql配置，Master为主节点，Slave为从节点
      MYSQL_MASTER_SERVICE_PORT: 3306
      MYSQL_MASTER_SERVICE_DB_NAME: nacos_config
      MYSQL_MASTER_SERVICE_USER: root
      MYSQL_MASTER_SERVICE_PASSWORD: root
      MYSQL_SLAVE_SERVICE_HOST: 101.34.180.133
      MYSQL_SLAVE_SERVICE_PORT: 3307
      #MYSQL_SLAVE_SERVICE_HOST: 10.2.7.29
      #MYSQL_SLAVE_SERVICE_PORT: 3341
      #JVM调优参数
      #JVM_XMS:  #-Xms default :2g
      #JVM_XMX:  #-Xmx default :2g
      #JVM_XMN:  #-Xmn default :1g
      #JVM_MS:   #-XX:MetaspaceSize default :128m
      #JVM_MMS:  #-XX:MaxMetaspaceSize default :320m
      #NACOS_DEBUG: n #是否开启远程debug，y/n，默认n
      #TOMCAT_ACCESSLOG_ENABLED: true #是否开始tomcat访问日志的记录，默认false
    volumes:
      - ./cluster-logs/nacos3:/home/nacos/logs #日志输出目录
      - ../init.d/custom.properties:/home/nacos/init.d/custom.properties #../init.d/custom.properties内包含很多自定义配置，可按需配置

networks:
  nacos_net:
    driver: bridge
